// DO NOT EDIT - generated by github.com/edwarnicke/imports-gen
package imports

import (
	_ "context"
	_ "encoding/binary"
	_ "io/ioutil"
	_ "net"
	_ "os"
	_ "path/filepath"
	_ "syscall"
	_ "testing"

	_ "github.com/edwarnicke/exechelper"
	_ "github.com/stretchr/testify/assert"
	_ "github.com/stretchr/testify/require"
)
