---
name: Pull Request on update/* Branch Push
on:
  push:
    branches:
      - update/*
jobs:
  auto-pull-request:
    name: Pull Request on update/* Branch Push
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
          BRANCH_PREFIX: "update/"
          PULL_REQUEST_BRANCH: "master"
