---
name: Update sdk-kernel
on:
  push:
    branches:
      - master
jobs:
  update-sdk-kernel:
    name: Update sdk-kernel
    runs-on: ubuntu-latest
    if: github.repository == 'networkservicemesh/sdk'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: networkservicemesh/sdk-kernel
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - name: Update sdk locally
        run: |
          GOPROXY=direct go get -u github.com/networkservicemesh/sdk
          go mod tidy
          git diff
      - name: Push update to sdk-kernel
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git add go.mod go.sum
          git commit -s -m "Update go.mod and go.sum to latest version from networkservicemesh/sdk@master"
          git checkout -b update/sdk-gomod
          git push -f origin update/sdk-gomod
